const fmt = new Intl.NumberFormat('es-MX');
const pct = v => `${(v*100).toFixed(1)}%`;
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const order = ['59th','50th','NW 23rd','MacArthur','Moore','Admiral','Garnett','Harvard','129th','Peoria','Broken Arrow'];
let summary, cards=[];

function kpi(label,value,note,cls=''){return `<article class="kpi ${cls}"><span>${label}</span><b>${value}</b><small>${note}</small></article>`}
function renderReview(r,cls){return `<article class="review-item ${cls}"><div class="review-meta"><span>${esc(r.date)}</span><span>${'★'.repeat(r.stars)}</span><span>${esc(r.reviewer)}</span></div><p>${esc(r.text)}</p><a href="${esc(r.url)}" target="_blank" rel="noopener">Abrir en Google ↗</a></article>`}
async function loadComments(slug,details){
  if(details.dataset.loaded==='1') return;
  const panel=details.querySelector('.reviews-panel');
  panel.innerHTML='<div class="loading-card">Cargando comentarios…</div>';
  try{
    const r=await fetch(`data/comments/${slug}.json`); const d=await r.json();
    const pos=d.positive.length?d.positive.map(x=>renderReview(x,'positive')).join(''):'<p class="empty">No hay positivos con texto.</p>';
    const neg=d.negative.length?d.negative.map(x=>renderReview(x,'negative')).join(''):'<p class="empty">No hay negativos con texto.</p>';
    panel.innerHTML=`<section><div class="review-col-title"><b>Positivos recientes</b><span>${d.positive.length}/10</span></div>${pos}</section><section><div class="review-col-title"><b>Negativos recientes</b><span>${d.negative.length}/10</span></div>${neg}</section>`;
    details.dataset.loaded='1';
  }catch(e){panel.innerHTML='<p class="empty">No se pudieron cargar los comentarios.</p>'}
}
function storeCard(s,index){
  const market=s.market==='OKC Metro'?'OKC':'Tulsa';
  return `<article class="store-card" data-market="${market}" data-rating="${s.rating}" data-neg="${(s.negative_pct*100).toFixed(2)}">
    <div class="store-top"><span class="store-num">${String(index).padStart(2,'0')}</span><div><h3>${esc(s.branch)}</h3><small>${esc(s.city)} · ${esc(s.market)}</small></div><div class="rating">${s.rating.toFixed(1)} ★<small>${fmt.format(s.google_total)} públicas</small></div></div>
    <div class="coverage-row"><span><b>${fmt.format(s.scraped_reviews)}</b>reviews analizadas</span><span><b>${pct(s.coverage)}</b>del contador público</span><span><b>${fmt.format(s.text_reviews)}</b>con texto</span></div>
    <div class="store-mid"><div class="donut" style="--pos:${s.positive_pct*100};--neu:${s.neutral_pct*100}"><span>${fmt.format(s.scraped_reviews)}<small>reviews</small></span></div><div class="legend"><div><i class="p"></i><span>Positivo</span><b>${pct(s.positive_pct)}</b><small>${fmt.format(s.positive_n)}</small></div><div><i class="m"></i><span>Neutral</span><b>${pct(s.neutral_pct)}</b><small>${fmt.format(s.neutral_n)}</small></div><div><i class="n"></i><span>Negativo</span><b>${pct(s.negative_pct)}</b><small>${fmt.format(s.negative_n)}</small></div></div></div>
    <div class="date-range">Periodo recuperado: ${s.first_date} → ${s.last_date}</div>
    <details data-slug="${s.slug}"><summary>Ver 10 comentarios positivos y negativos recientes</summary><div class="reviews-panel"></div></details>
  </article>`
}
function missingCard(index){return `<article class="store-card missing" data-market="Tulsa" data-rating="0" data-neg="0"><div class="store-top"><span class="store-num">${String(index).padStart(2,'0')}</span><div><h3>Admiral</h3><small>Tulsa · Tulsa Metro</small></div><div class="badge unavailable">Sin datos</div></div><div class="missing-body"><b>Esta sucursal no viene en el CSV recibido.</b><p>No se incluye en sentiment, comparativas ni temas para evitar completar el dato con una fuente distinta.</p></div></article>`}
function applyFilters(){
  const m=document.getElementById('marketFilter').value,r=document.getElementById('ratingFilter').value,n=document.getElementById('negFilter').value;
  let visible=0;
  cards.forEach(c=>{let show=true;if(m!=='all')show=show&&c.dataset.market===m;if(!c.classList.contains('missing')){const rating=+c.dataset.rating,neg=+c.dataset.neg;if(r==='high')show=show&&rating>=4.4;if(r==='mid')show=show&&rating===4.3;if(r==='low')show=show&&rating<=4.2;if(n==='high')show=show&&neg>=12;if(n==='mid')show=show&&neg>=9&&neg<12;if(n==='low')show=show&&neg<9}else if(r!=='all'||n!=='all') show=false;c.hidden=!show;if(show)visible++});
  const active=[m,r,n].filter(v=>v!=='all').length;document.getElementById('filterStatus').textContent=`Mostrando ${visible} de ${cards.length} sucursales${active?` · ${active} filtro${active===1?'':'s'} activo${active===1?'':'s'}`:''}`;document.getElementById('resetFilters').textContent=active?`Restablecer (${active})`:'Restablecer';
}
async function init(){
  const res=await fetch('data/summary.json?v=20260812-1'); summary=await res.json(); const o=summary.overall;
  document.getElementById('heroCopy').textContent=`Sentiment calculado sobre todos los registros únicos recuperados en el CSV recibido. Los porcentajes ya no provienen de una muestra de cinco reseñas: se calculan con las estrellas de las ${fmt.format(o.scraped_reviews)} reviews disponibles.`;
  const coverage=o.scraped_reviews/o.google_total_dataset_stores;
  document.getElementById('integrityNote').innerHTML=`<b>Cobertura del archivo:</b> ${fmt.format(o.scraped_reviews)} reviews recuperadas de ${fmt.format(o.google_total_dataset_stores)} calificaciones públicas reportadas en las 10 fichas presentes (${pct(coverage)}). El CSV no contiene Admiral y varias tiendas parecen topadas por el scraper; por eso el reporte habla de <b>reviews recuperadas/analizadas</b>, no de 100% histórico de Google.`;
  const weighted=summary.stores.reduce((a,s)=>a+s.rating*s.google_total,0)/summary.stores.reduce((a,s)=>a+s.google_total,0);
  document.getElementById('kpis').innerHTML=kpi('Reviews analizadas',fmt.format(o.scraped_reviews),`${fmt.format(o.unique_reviews)} review IDs únicos · Google`)+kpi('Rating público ponderado',`${weighted.toFixed(2)} ★`,'10 fichas presentes en el CSV')+kpi('Positivo',pct(o.positive_pct),`${fmt.format(o.positive_n)} reviews 4–5★`,'pos')+kpi('Neutral',pct(o.neutral_pct),`${fmt.format(o.neutral_n)} reviews 3★`)+kpi('Negativo',pct(o.negative_pct),`${fmt.format(o.negative_n)} reviews 1–2★`,'neg');
  document.getElementById('marketGrid').innerHTML=summary.markets.map(m=>{const note=m.market==='OKC Metro'?'5 de 5 sucursales presentes en el CSV':'5 de 6 sucursales presentes; Admiral no está incluido';return `<article class="market-card"><div class="market-top"><div><span class="market-name">${m.market}</span><small>${note}</small></div><div class="market-rating">${m.rating_weighted.toFixed(2)} ★<small>rating público ponderado</small></div></div><div class="market-kpis"><div><span>Reviews analizadas</span><b>${fmt.format(m.scraped_reviews)}</b></div><div><span>Positivo</span><b>${pct(m.positive_pct)}</b></div><div><span>Neutral</span><b>${pct(m.neutral_pct)}</b></div><div><span>Negativo</span><b>${pct(m.negative_pct)}</b></div></div><div class="market-bar"><i class="p" style="width:${m.positive_pct*100}%"></i><i class="m" style="width:${m.neutral_pct*100}%"></i><i class="n" style="width:${m.negative_pct*100}%"></i></div></article>`}).join('');
  const map=Object.fromEntries(summary.stores.map(s=>[s.branch,s]));document.getElementById('storeGrid').innerHTML=order.map((b,i)=>b==='Admiral'?missingCard(i+1):storeCard(map[b],i+1)).join('');cards=[...document.querySelectorAll('.store-card')];cards.forEach(c=>{const d=c.querySelector('details');if(d)d.addEventListener('toggle',()=>{if(d.open)loadComments(d.dataset.slug,d)})});
  const rank=[...summary.stores].sort((a,b)=>b.positive_pct-a.positive_pct);document.getElementById('rankList').innerHTML=rank.map(s=>`<div class="rank-row"><span>${s.branch}</span><i><b style="width:${s.positive_pct*100}%"></b></i><strong>${pct(s.positive_pct)}</strong><small>${fmt.format(s.scraped_reviews)} reviews</small></div>`).join('');
  document.getElementById('topicEyebrow').textContent=`${fmt.format(o.text_reviews)} reviews con texto`;document.getElementById('topicGrid').innerHTML=summary.topics.slice(0,8).map(t=>`<article class="topic-card"><div class="topic-head"><b>${t.topic}</b><span>${fmt.format(t.mentions)}</span></div><div class="topic-bar"><i class="p" style="width:${t.positive_n/t.mentions*100}%"></i><i class="m" style="width:${t.neutral_n/t.mentions*100}%"></i><i class="n" style="width:${t.negative_n/t.mentions*100}%"></i></div><small>${fmt.format(t.positive_n)} positivas · ${fmt.format(t.neutral_n)} neutrales · ${fmt.format(t.negative_n)} negativas</small></article>`).join('');
  const by=Object.fromEntries(summary.stores.map(s=>[s.branch,s])),okc=summary.markets.find(m=>m.market==='OKC Metro'),tulsa=summary.markets.find(m=>m.market==='Tulsa Metro');const insights=[['El corpus recuperado es mayoritariamente positivo',`De las ${fmt.format(o.scraped_reviews)} reviews únicas del CSV, ${pct(o.positive_pct)} son 4–5★, ${pct(o.neutral_pct)} son 3★ y ${pct(o.negative_pct)} son 1–2★.`],['Broken Arrow muestra la distribución más favorable del archivo',`Registra ${pct(by['Broken Arrow'].positive_pct)} positivo sobre ${fmt.format(by['Broken Arrow'].scraped_reviews)} reviews analizadas y un rating público de ${by['Broken Arrow'].rating.toFixed(1)}★.`],['Harvard concentra la mayor proporción negativa',`Harvard registra ${pct(by['Harvard'].negative_pct)} negativo sobre ${fmt.format(by['Harvard'].scraped_reviews)} reviews recuperadas; NW 23rd le sigue con ${pct(by['NW 23rd'].negative_pct)}.`],['Tulsa y OKC se mantienen relativamente cercanos',`En el corpus recuperado, Tulsa marca ${pct(tulsa.positive_pct)} positivo frente a ${pct(okc.positive_pct)} en OKC. Tulsa no incluye Admiral en este archivo.`],['La cobertura de extracción cambia por tienda',`MacArthur está completo frente a su contador público; otras fichas están entre aproximadamente 26% y 82%. Por eso se distingue reviews analizadas de total público Google.`],['Comida preparada y servicio concentran más menciones',`Sobre ${fmt.format(o.text_reviews)} reviews con texto, Food service/comida preparada y Servicio y trato son los tags con más menciones. El tagging es por palabras clave.`]];document.getElementById('insightGrid').innerHTML=insights.map((x,i)=>`<article><span>0${i+1}</span><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('');
  document.getElementById('methodCopy').innerHTML=`<b>Sentiment:</b> 4–5★ = positivo, 3★ = neutral, 1–2★ = negativo. Se calcula sobre las ${fmt.format(o.scraped_reviews)} filas únicas del CSV, sin muestreo adicional. <b>Texto:</b> ${fmt.format(o.text_reviews)} registros contienen comentario escrito y se usan para ejemplos y temas. <b>Cobertura:</b> el archivo representa ${pct(coverage)} del contador público agregado de las 10 fichas presentes; varias extracciones están topadas en 500 registros y Admiral no está incluido. Los datos cubren publicaciones entre ${o.first_date} y ${o.last_date}.`;
  ['marketFilter','ratingFilter','negFilter'].forEach(id=>document.getElementById(id).addEventListener('change',applyFilters));document.getElementById('resetFilters').addEventListener('click',()=>{['marketFilter','ratingFilter','negFilter'].forEach(id=>document.getElementById(id).value='all');applyFilters()});applyFilters();
}
init().catch(err=>{document.getElementById('heroCopy').textContent='No se pudo cargar la base procesada.';console.error(err)});
